// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-about.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_about_default = defineTool({
  name: "get_about",
  title: "Get About Info",
  description: "Get Keshihan's personal bio, current role, education summary, certifications, and languages spoken.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({
          name: "Keshihan Ilamuruganathan",
          location: "Trincomalee, Sri Lanka",
          bio: "Keshihan is a dedicated and ambitious professional with a strong passion for Information Technology and Business Management. He is a passionate social impactpreneur from Trincomalee, Sri Lanka, dedicated to driving innovation at the intersection of technology, digital marketing & community empowerment.",
          currentRole: "Analyst (Business + Social Media)",
          education: "BSc. Information Systems",
          certifications: "2\xD7 Salesforce \xB7 Cisco Certified",
          languages: ["Tamil", "English", "Sinhala", "French"]
        }, null, 2)
      }
    ]
  })
});

// src/lib/mcp/tools/get-experience.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_experience_default = defineTool2({
  name: "get_experience",
  title: "Get Work Experience",
  description: "Get Keshihan's professional work experience history in reverse chronological order.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify([
          {
            role: "Social Media Analyst",
            company: "Qubitz",
            period: "Feb 2025 \u2013 Present",
            description: "Analyze social media performance and generate data-driven insights to optimize engagement and campaign effectiveness. Manage brand presence by developing strategic content, tracking trends, and improving overall digital growth."
          },
          {
            role: "Business Analyst Intern",
            company: "Dialog Axiata PLC",
            period: "Aug 2024 \u2013 Feb 2025",
            description: "Developed and maintained dynamic sales dashboards (weekly/monthly/quarterly) to track performance metrics. Analyzed sales trends, market insights, and partner performance to identify gaps and recommend improvements."
          },
          {
            role: "Social Media Analyst",
            company: "Hashtag Generation",
            period: "Sep 2024 \u2013 Feb 2025",
            description: "Monitored platform-specific trends and audience behavior to optimize content strategy. Prepared performance reports and analyzed campaign results for data-driven decision-making."
          },
          {
            role: "Development Intern",
            company: "International Youth Alliance for Peace (IYAP)",
            period: "Feb 2023 \u2013 Jul 2023",
            description: "Worked on graphic designing, social media management, strategy planning, blogging, article writing, and the blogger recruitment project."
          },
          {
            role: "Digital Marketing Intern",
            company: "Commercial Technologies Plus",
            period: "Aug 2022 \u2013 Feb 2023",
            description: "Assisted in executing digital campaigns, optimizing content strategies, and contributing to brand visibility across multiple online platforms."
          }
        ], null, 2)
      }
    ]
  })
});

// src/lib/mcp/tools/get-education.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_education_default = defineTool3({
  name: "get_education",
  title: "Get Education",
  description: "Get Keshihan's academic qualifications and educational background.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify([
          { degree: "Bachelor of Laws (Hons)", institution: "Open University of Sri Lanka", period: "2024 \u2013 Present" },
          { degree: "Diploma in Digital Marketing", institution: "Sri Lanka Institute of Marketing", period: "2023 \u2013 2024" },
          { degree: "Diploma in Political Studies", institution: "Centenary Political Academy", period: "2023 \u2013 2024" },
          { degree: "BA in Sustainable Development", institution: "Xavier University, Odisha", period: "2022 \u2013 2026" },
          { degree: "BSc. (Hons) in Information Systems", institution: "Sabaragamuwa University of Sri Lanka", period: "2021 \u2013 2025" }
        ], null, 2)
      }
    ]
  })
});

// src/lib/mcp/tools/get-certifications.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_certifications_default = defineTool4({
  name: "get_certifications",
  title: "Get Certifications",
  description: "Get Keshihan's professional certifications and credentials.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify([
          { name: "Salesforce Certified AI Associate", issuer: "Salesforce" },
          { name: "Salesforce Certified Platform Foundations", issuer: "Salesforce" },
          { name: "Cisco Certified Cybersecurity Essentials", issuer: "Cisco" },
          { name: "Certified Aspire Scholar 2023", issuer: "Aspire Institute" },
          { name: "Diploma in Digital Marketing", issuer: "Sri Lanka Institute of Marketing" },
          { name: "Google Analytics Certification", issuer: "Google" }
        ], null, 2)
      }
    ]
  })
});

// src/lib/mcp/tools/get-achievements.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_achievements_default = defineTool5({
  name: "get_achievements",
  title: "Get Achievements",
  description: "Get Keshihan's achievements, awards, hackathon results, and recognitions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify([
          { title: "Lazarus 2.0 EIDOS Ideathon \u2014 Winners", year: "2023" },
          { title: "Yarl SF Ohana Hackforce \u2014 Finalist", year: "2023" },
          { title: "Idealize 3.0 \u2014 Finalist", year: "2022" },
          { title: "Aspire Scholar '23", description: "Selected for the Aspire Leaders Program." },
          { title: "Social Impactpreneur", description: "Driving community empowerment initiatives through technology in Sri Lanka." },
          { title: "5,600+ LinkedIn Followers", description: "Strong professional network sharing insights on tech, marketing, and career development." }
        ], null, 2)
      }
    ]
  })
});

// src/lib/mcp/tools/get-competencies.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_competencies_default = defineTool6({
  name: "get_competencies",
  title: "Get Skills & Competencies",
  description: "Get Keshihan's technical skills and competencies grouped by category.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({
          programming: ["Python", "JavaScript", "SQL", "HTML5", "CSS3"],
          frameworksAndTools: ["React Native", "Flutter", "Bootstrap", "WordPress", "GitHub Pages"],
          designAndMedia: ["Figma", "Canva", "Adobe Photoshop", "Adobe Lightroom", "Filmora WS"],
          dataAndAnalytics: ["Google Analytics", "MySQL", "Business Analysis", "Data Visualization", "Jira"],
          marketingAndContent: ["Social Media Marketing", "SEO", "Content Writing", "Digital Advertising", "Blogging"],
          projectManagement: ["Trello", "Jira", "Slack", "Microsoft Teams", "Microsoft Packages"],
          platforms: ["Salesforce", "Hosting", "WordPress", "Zoom", "Translation"],
          interests: ["Photography", "Volunteering", "Blogging", "Mentoring"]
        }, null, 2)
      }
    ]
  })
});

// src/lib/mcp/tools/get-services.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_services_default = defineTool7({
  name: "get_services",
  title: "Get Services Offered",
  description: "Get the list of professional services Keshihan offers to clients.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify([
          { title: "Digital Marketing", description: "Data-driven social media strategy, SEO, and paid campaigns that grow reach and conversions." },
          { title: "Content Creation", description: "Engaging written, visual, and video content crafted to elevate your brand story." },
          { title: "Business Coaching", description: "Practical guidance for founders and teams to sharpen strategy, execution, and growth." },
          { title: "Voice-Over Services", description: "Clear, professional voice-overs for ads, explainers, and e-learning in multiple languages." },
          { title: "Career Coaching", description: "Personalised mentoring on CVs, interviews, and career direction for students and professionals." },
          { title: "Full-Stack Development", description: "End-to-end web and mobile applications built with modern, scalable technologies." }
        ], null, 2)
      }
    ]
  })
});

// src/lib/mcp/tools/get-projects.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_projects_default = defineTool8({
  name: "get_projects",
  title: "Get Featured Projects",
  description: "Get Keshihan's featured work and projects with links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify([
          {
            title: "Arts & Culture Hub",
            tags: ["Arts & Culture", "Youth"],
            description: "Akaram Kalaikoodam \u2014 an organization shaping Trincomalee's youth future through arts, culture, and creative expression.",
            link: "https://akaramkalaikoodam.com/"
          },
          {
            title: "Community Hub Trinco Mirror",
            tags: ["Community", "Web Dev"],
            description: "A community-driven news and information hub serving the Trincomalee district.",
            link: "https://trincomirror.com/"
          },
          {
            title: "Digital Marketing Campaigns",
            tags: ["Marketing", "Analytics"],
            description: "End-to-end social media campaigns with data-driven insights and measurable ROI for multiple brands.",
            link: "https://qubitz.solutions/"
          }
        ], null, 2)
      }
    ]
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_contact_default = defineTool9({
  name: "get_contact",
  title: "Get Contact & Social Info",
  description: "Get Keshihan's contact information, email, phone, and social media handles.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({
          email: "keshihan0000@gmail.com",
          phone: "+94 77 918 5685",
          location: "Trincomalee, Sri Lanka",
          social: {
            linkedin: "https://www.linkedin.com/in/keshihan/",
            github: "https://github.com/keshihan019",
            facebook: "https://www.facebook.com/growithkeshican",
            instagram: "https://www.instagram.com/keshihan_19",
            twitter: "https://x.com/keshihan019",
            youtube: "https://www.youtube.com/channel/UCewC3HIV1PW4iQFncs8Nqxw",
            tiktok: "https://www.tiktok.com/@keshihan_19",
            medium: "https://medium.com/@keshihan",
            behance: "https://behance.net/keshihan",
            hackerrank: "https://www.hackerrank.com/keshihan0000",
            stackoverflow: "https://stackoverflow.com/users/20063836/keshihan-ilamuruganathan"
          },
          freelance: {
            fiverr: "https://www.fiverr.com/keshihan",
            upwork: "https://www.upwork.com/freelancers/~015084858ff12e8415",
            freelancer: "https://www.freelancer.com/u/keshihan19"
          }
        }, null, 2)
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "keshihan-portfolio-mcp",
  title: "Keshihan Portfolio MCP",
  version: "0.1.0",
  instructions: "Provides read-only access to Keshihan Ilamuruganathan's public professional portfolio. Use these tools to answer questions about his background, experience, education, skills, certifications, achievements, services, projects, and contact information.",
  tools: [
    get_about_default,
    get_experience_default,
    get_education_default,
    get_certifications_default,
    get_achievements_default,
    get_competencies_default,
    get_services_default,
    get_projects_default,
    get_contact_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
